### PR TITLE
feat(body): add support for graphql mutation and optional identifier

### PR DESCRIPTION
**Pull request by seblj**
It should also capture `mutation` as a graphql body. I also added support for an optional identifier for the query/mutation.

### CODE REVIEW

**Comment by NTBBloodbath** [comment]
Hi there, could you please rebase your PR with the latest repository changes?

I've recently merged #28 and it seems like GitHub didn't like the formatting changes, sorry for the inconveniences :p

**Comment by seblj** [comment]
Done😄

**Comment by seblj** [comment]
I have another thing I would like to fix if you don't mind? It is the requirement of having a `(` for the query. It is not needed if there is no variables

**Comment by NTBBloodbath** [comment]
> I have another thing I would like to fix if you don't mind? It is the requirement of having a `(` for the query. It is not needed if there is no variables

Sounds good to me, let me know once the changes are done to merge them :p

**Comment by seblj** [comment]
Now I am finished😄 This seems to work. I also added a couple of tests for the things I added support for

**Review by NTBBloodbath — APPROVED** [review]
Testing CIs are passing so it's fine to merge, thank you so much for these changes! :)

**Pull request merged**
