### PR TITLE
refactor!: Refactor spec

### LINKED ISSUE #18: Feature: Spread query parameters into multiple lines
Is there a way to let query strings more human-readable as this vscode extension does? 

https://marketplace.visualstudio.com/items?itemName=humao.rest-client
Screen Shot 2022-06-15 at 10 17 26 AM

### LINKED ISSUE #19: Feature: break long lines
image

### LINKED ISSUE #29: [Bug] Can't recognize the variable in header
image

The `{{TOKEN}}` in this case, is parsed as `value`, instead of `variable`.

The header should be parsed to 
```
  header
    name: name
    value: value
    value: value
    value: variable
      name: identifier
```

### LINKED ISSUE #30: Allow additional characters in Authorisation credentials
I'm getting an error when trying to use `=` inside my `Authorisation` value.

For example, using;

```
Authorisation: Basic YmQ0NT02NTM4YWE5ND03MzJkMTdlN0RiNTdkOGFj0TAwZjhkZj0mYTp5Qzc4aDgmZW85R1A=
```

results in:

```
Error executing Lua callback: .../share/nvim/lazy/rest.nvim/lua/rest-nvim/parser/init.lua:114: attempt to index local 'req_node' (a nil value)
stack traceback:
	.../share/nvim/lazy/rest.nvim/lua/rest-nvim/parser/init.lua:114: in function 'traverse_request'
	.../share/nvim/lazy/rest.nvim/lua/rest-nvim/parser/init.lua:432: in function 'parse'
	...al/share/nvim/lazy/rest.nvim/lua/rest-nvim/functions.lua:61: in function 'exec'
	...cal/share/nvim/lazy/rest.nvim/lua/rest-nvim/commands.lua:44: in function 'impl'
	...cal/share/nvim/lazy/rest.nvim/lua/rest-nvim/commands.lua:182: in function <...cal/share/nvim/lazy/rest.nvim/lua/rest-nvim/commands.lua:165>
```

This seems related to https://github.com/rest-nvim/tree-sitter-http/pull/23 where it mentions `=` being disabled for URLs.

### LINKED ISSUE #31: `application/json;v=2` or similar setups in the Accept header are not accepted by parser
When attempting to run the below request...
```http
GET https://reqres.in/api/users?page=5
Accept: application/json;v=2
```

...I get the following error:
```
[rest.nvim] ERROR: The tree-sitter node at the range [0:0 - 1:28] has a syntax error and cannot be parsed
Error executing Lua callback: .../share/nvim/lazy/rest.nvim/lua/rest-nvim/parser/init.lua:143: attempt to index local 'document_node' (a nil value)
stack traceback:
        .../share/nvim/lazy/rest.nvim/lua/rest-nvim/parser/init.lua:143: in function 'traverse_variables'
        .../share/nvim/lazy/rest.nvim/lua/rest-nvim/parser/init.lua:436: in function 'parse'
        ...al/share/nvim/lazy/rest.nvim/lua/rest-nvim/functions.lua:61: in function 'exec'
        ...cal/share/nvim/lazy/rest.nvim/lua/rest-nvim/commands.lua:44: in function 'impl'
        ...cal/share/nvim/lazy/rest.nvim/lua/rest-nvim/commands.lua:182: in function <...cal/share/nvim/lazy/rest.nvim/lua/rest-nvim/commands.lua:165>
```

> Note: the example request wouldn't give a different response from `Accept: application/json`, but this is just an example of a setup that I would expect to work and works for normal cURL requests.

Is this something that could be easy to fix? I'd be glad to fix it, but I don't understand enough about the parser to know where to look.

### LINKED ISSUE #33: [Feature] Add support for variables as query params values.
I opened a PR for adding this feature but also open this issue if you want to discuss the matter. Thanks!

### LINKED ISSUE #35: [BUG] The '{' and '}' in the target_url are recognized as ERROR
The following request will not resolve successfully:

```
GET http://localhost:5000/index?userProperty={"name": "age"}
```

This kind of query_param with JSON information is also encountered in the actual development process, but it is not currently possible to parse

### PR DESCRIPTION
**Pull request by boltlessengineer**
refactor the parser following more well-known [spec]. This resolves most opened issues.

- change bunch of node names and fields
- make request method optionable
- disallow whitespace in front of request
- multi-line target_url by indented lines
- require blank line between URL+header & body
- require `###` separator between each requests
- don't parse url scheme and stuffs (not worth it)
- support `//` comment
- allows whitespace in form-data
- variables are always parsed as raw string. numbers, `true|false`, quotes don't have any meanings
- response handler script will use `{% ... %}` syntax and injected language is javascript by default (unless you put `# @lang=lua` above)

fixed #18
fixed #19
fixed #29
fixed #30
fixed #31
fixed #33
fixed #35

I forgot to sync my local repo before I start working, I’ll rebase this manually soon.

- [x] manual rebase from main
- [ ] update test cases

Edit: add todo

[spec]: https://www.jetbrains.com/help/idea/exploring-http-syntax.html

### CODE REVIEW

**Comment by NTBBloodbath** [comment]
Note: I'm not sure about [adding rest.nvim stuff back](https://github.com/rest-nvim/tree-sitter-http/pull/36/commits/e5d4227f12399016ce989cd2d53d69fe98665154), I've completely stopped working on the project and archived it. Unless someone is going to work on a fork or re-use some of the functionality it has, because this PR completely refactors the specs from what I understand.

@gorillamoe I'm not sure if you guys are using this http parser or reusing rest.nvim functionalities that were made possible by the parser (e.g. Lua scripting) in kulala.nvim, so I'd appreciate some input here if possible.

**Comment by gorillamoe** [comment]
We're just "relying" on the TS HTTP grammar for syntax highlighting. So it wouldn't break things for kulala ❤️

**Comment by boltlessengineer** [comment]
> Unless someone is going to work on a fork or re-use some of the functionality it has

@NTBBloodbath You just discovered secret commit message. :)
Yes, I am working on rest.nvim fork since couple of days ago.

I'm rewriting most of the functionalities from v2 but it still shares same mindset (e.g. using tree-sitter for parsing, luarocks dependencies for many stuffs, same result & winbar UI)

Can I get access to rest-nvim project? If you want to keep rest.nvim archived, I can just make separate fork repo (like rest3.nvim or something) but since it heavily depends on this tree-sitter parser, it will be grateful if I can maintain both.
I was going to ask this when the fork is ready. It will take few more days to be done.

**Comment by NTBBloodbath** [comment]
> > Unless someone is going to work on a fork or re-use some of the functionality it has
> 
> @NTBBloodbath You just discovered secret commit message. :)
> Yes, I am working on rest.nvim fork since couple of days ago.
> 
> I'm rewriting most of the functionalities from v2 but it still shares same mindset (e.g. using tree-sitter for parsing, luarocks dependencies for many stuffs, same result & winbar UI)

Oh, I didn't expect something like this to happen lol. Glad to know someone is doing it :p

> Can I get access to rest-nvim project? If you want to keep rest.nvim archived, I can just make separate fork repo (like rest3.nvim or something) but since it heavily depends on this tree-sitter parser, it will be grateful if I can maintain both.
> I was going to ask this when the fork is ready. It will take few more days to be done.

Sure, I don't see a problem with it. If you want to work on the existing repository, it can also be unarchived so whatever works best for you. I will send you an invitation to the organization right now, and let me know if you need anything else.

Cheers

**Comment by askfiy** [comment]
How is the current progress of this PR? looking forward.

**Comment by boltlessengineer** [comment]
@askfiy hi, as I’m also rewriting [rest.nvim] for v3 release in same time, I’m going to merge this PR when both plugin and the parser is ready.
Because both are having major version upgrades, I think releasing two v3.0.0 in same time makes sense.

[rest.nvim] rewrite is almost ready. I’ll open the v3 branch to public soon. It will be merged in a week or two.

[rest.nvim]: https://github.com/rest-nvim/rest.nvim

**Comment by askfiy** [comment]
Thanks for your work, I'm also waiting for this PR to be merged to release the new plugin.

**Pull request closed without merging**
